name: "Build and Test"
on: ["push", "pull_request"]

jobs:
    TestOnMacOS-Latest-x86_64:
        runs-on: "macos-latest"
        steps:
            - uses: "actions/checkout@v2"
            - name: "Install Dependencies"
              run: |
                  brew update
                  brew install sqlite unixodbc sqliteodbc psqlodbc

                  brew services start postgresql

                  echo "Check PostgreSQL service is running"
                  i=10
                  COMMAND='pg_isready'
                  while [ $i -gt 0 ]; do
                      echo "Check PostgreSQL service status"
                      eval $COMMAND && break
                      ((i--))
                      if [ $i == 0 ]; then
                          echo "PostgreSQL service not ready, all attempts exhausted"
                          exit 1
                      fi
                      echo "PostgreSQL service not ready, wait 10 more sec, attempts left: $i"
                      sleep 10
                  done

                  #psql --command="\du;" -U $(echo $USER)

                  #createdb --owner=postgres testdb
                  #PGPASSWORD=postgres psql --username=postgres --host=localhost --list testdb

                  # Based on https://github.com/nanodbc/nanodbc/blob/master/utility/ci/travis/before_script.sqlite.sh
                  # and https://github.com/nanodbc/nanodbc/blob/master/utility/ci/travis/before_install.osx.sh

                  cat $(odbc_config --odbcinstini)

                  SQLITE_DRIVER=$(brew ls -v sqliteodbc | grep libsqlite3odbc.dylib)

                  cat > "$(odbc_config --odbcinstini)" <<EOF
                  [PostgreSQL]
                  Description = PostgreSQL ODBC Driver
                  Driver = $(brew ls psqlodbc -v | grep psqlodbcw.so)

                  [SQLite3]
                  Description = SQLite3 ODBC Driver
                  Driver = $SQLITE_DRIVER
                  Setup = $SQLITE_DRIVER
                  Threading = 2
                  EOF

                  cat $(odbc_config --odbcinstini)
            - name: "Run Tests"
              run: |
                  export POSTGRES_CONNECTION_STRING="Driver={PostgreSQL};Database=postgres;UID=postgres;Server=localhost;"
                  swift test -Xlinker "$(pkg-config --libs-only-L odbc)"
    TestOnUbuntu20_04-x86_64:
        runs-on: "ubuntu-20.04"
        steps:
            - uses: "actions/checkout@v2"
            - name: "Setup Databases"
              run: |
                  sudo apt update -q
                  sudo apt install -yq unixodbc-dev unixodbc odbc-postgresql libsqliteodbc libsqlite3-dev sqlite3

                  sudo systemctl start postgresql.service
                  pg_isready

                  sudo odbcinst -i -d -f /usr/share/sqliteodbc/unixodbc.ini
                  #sudo odbcinst -i -d -f /usr/share/psqlodbc/odbcinst.ini.template
            - name: "Run Tests"
              run: |
                  cat /etc/odbcinst.ini
                  export POSTGRES_CONNECTION_STRING="Driver={PostgreSQL ANSI};Database=postgres;UID=postgres;Server=localhost;"
                  swift test
