name: "Build and Test"
on: ["push", "pull_request"]

jobs:
  TestOnMacOS-11_0-x86_64:
    runs-on: "macos-11.0"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Install Dependencies"
      run: |
        brew update
        brew install sqlite unixodbc sqliteodbc psqlodbc

        # Based on https://github.com/nanodbc/nanodbc/blob/master/utility/ci/travis/before_script.sqlite.sh
        # and https://github.com/nanodbc/nanodbc/blob/master/utility/ci/travis/before_install.osx.sh
        cat > "$(odbc_config --odbcinstini)" <<EOF
        [PostgreSQL]
        Description = PostgreSQL ODBC Driver
        Driver = $(brew ls psqlodbc -v | grep psqlodbcw.so)
        [SQLite3]
        Description = SQLite3 ODBC Driver
        Driver = $(brew ls -v sqliteodbc | grep libsqlite3odbc.dylib)
        EOF
    - name: "Run Tests"
      run: |
        sudo xcode-select -s /Applications/Xcode_12.5.app
        swift test -Xlinker "$(pkg-config --libs-only-L odbc)"
